### ISSUE TITLE
Videos not available in google drive

### ISSUE THREAD

**Issue by fazliimam** [Jason-Qiu/MultiSum_model#2]
Hi, where can I download the videos?

**Comment by Jielin-Qiu** [comment]
Hi Mohamed, you can find the video links in the annotation file. Thanks.

**Comment by fiht86** [comment]
> Hi, where can I download the videos?

hi,Did you find the link to the video?

**Comment by lousiming** [comment]
> Hi, where can I download the videos?

Could you let me know if you downloaded the original video? If you did, could you please send me a message? It would be very helpful for me, and I hope you can assist me with this.

**Comment by lousiming** [comment]
> > Hi, where can I download the videos?
> 
> hi,Did you find the link to the video?

Could you let me know if you downloaded the original video? If you did, could you please send me a message? It would be very helpful for me, and I hope you can assist me with this.
