### ISSUE TITLE
how can i use  this model to inference my own data

### ISSUE THREAD

**Issue by 1ighter** [Jason-Qiu/MultiSum_model#3]
I've seen the code from processing, but i only see the code for the exist dataset from the link, if i only want to inference my dataset(only video and the text context), do i need to build the same annotation json file, thanks!

**Comment by 1ighter** [comment]
i mean when i use this model to generate thumbnail, how can i use my own data

**Comment by dreamerlin** [comment]
Same question

**Comment by willxxy** [comment]
Hi @1ighter and @dreamerlin ,

Thanks for the interest in our work.
In the case of fitting on your own dataset, it would be best if you built your dataset on the existing data structure in our method (e.g., the same annotation json file format).
We provide some insight on how the data was collected in this [repo](https://github.com/Jason-Qiu/MMSum_Data_Collection_Tool). 

Hopefully this helps! Thanks.

**Comment by lousiming** [comment]
> I've seen the code from processing, but i only see the code for the exist dataset from the link, if i only want to inference my dataset(only video and the text context), do i need to build the same annotation json file, thanks!

Could you let me know if you downloaded the original video? If you did, could you please send me a message? It would be very helpful for me, and I hope you can assist me with this.

**Comment by lousiming** [comment]
> Same question

Could you let me know if you downloaded the original video? If you did, could you please send me a message? It would be very helpful for me, and I hope you can assist me with this.
