### ISSUE TITLE
To clarify, does the term "thumbnail" in this context refer to selected keyframes from the segment?

### ISSUE THREAD

**Issue by sjl-git** [Jason-Qiu/MultiSum_model#6]
I am little confused.
Just to clarify, does the "thumbnail" feature you provide refer to keyframes selected by the video summary model?
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/5f745be9-2d51-4862-8bac-a73d027e5c2c">

**Comment by lousiming** [comment]
> I am little confused. Just to clarify, does the "thumbnail" feature you provide refer to keyframes selected by the video summary model? <img alt="image" width="1100" src="https://private-user-images.githubusercontent.com/55732695/384898548-5f745be9-2d51-4862-8bac-a73d027e5c2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODA4NDEsIm5iZiI6MTczMjU4MDU0MSwicGF0aCI6Ii81NTczMjY5NS8zODQ4OTg1NDgtNWY3NDViZTktMmQ1MS00ODYyLThiYWMtYTczZDAyN2U1YzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDAwMjIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmYmY2OGQ5MjlmNzRlMTEwZGM4NmVjNzMzODBmZTRmN2EwYjU4OWZjN2Q5MTE2Y2I5OTBmNGIxY2MyMjMwYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PuWbhKKyxpFlUdD_psVuIsvXFf9YVQQ9E0wlZGQ4aFg">

Could you let me know if you downloaded the original video? If you did, could you please send me a message? It would be very helpful for me, and I hope you can assist me with this.

**Comment by sjl-git** [comment]
@lousiming I downloaded original video using [yt-dlp](https://github.com/yt-dlp/yt-dlp).
You can find youtube urls on [mmsum annotations](https://drive.google.com/drive/folders/1ZE3p7JmoZe0EK-HIxpKrYUdHqXwFabUf?usp=sharing).

**Comment by lousiming** [comment]
@sjl-git Thank you for replying to me. May I ask if you have finished uploading all the videos? I am currently annotating the videos from the URL, but some of the video links are no longer valid, and I am unable to download them. Could I request an email from you to ask for the links to these videos?

**Comment by sjl-git** [comment]
@lousiming What do you mean by uploading the videos?
Some videos could be no longer valid as they could be outdated. Also, I didn't use any links other than the ones given by Jielin-Qiu.

**Comment by lousiming** [comment]
@sjl-git Sorry for the misunderstanding. What I meant is that I’ve been trying to download the videos using the links provided by Jielin-Qiu, but I noticed that in some categories, about 2-3 videos are no longer valid. I was wondering if you also encountered this issue when you were downloading the videos. Were you able to download all of them successfully? If not, approximately how many videos were missing?

**Comment by sjl-git** [comment]
@lousiming I only downloaded a subset of the videos about 1200 and encountered a similar issue. I failed to download one video, though I'm not sure.
