### ISSUE TITLE
Request for Assistance with Missing Videos in MMSum Dataset

### ISSUE THREAD

**Issue by lousiming** [Jason-Qiu/MultiSum_model#8]
I am a graduate student from China, and I am very interested in your work on the MMSum dataset.

While working with the dataset, I encountered some issues. Specifically, I have been trying to download the YouTube videos using the links provided in the annotation files. However, I noticed that in some subcategories, at least 2-3 videos are no longer available.

I wanted to ask if you might have already downloaded these videos. If so, would it be possible to share a Google Drive link or any other method for me to access the missing videos? I sincerely request your assistance, as this would be incredibly helpful for my research.

Thank you very much for your time and support!

**Comment by wsjqkd** [comment]
> 我是一名来自中国的研究生，我对您在 MMSum 数据集上的工作非常感兴趣。
> 
> 在处理数据集时，我遇到了一些问题。具体来说，我一直在尝试使用注释文件中提供的链接下载 YouTube 视频。但是，我注意到在某些子类别中，至少有 2-3 个视频不再可用。
> 
> 我想问问您是否已经下载了这些视频。如果是这样，是否可以共享 Google Drive 链接或任何其他方法供我访问丢失的视频？我真诚地请求您的帮助，因为这对我的研究非常有帮助。
> 
> 非常感谢您的时间和支持！

**Comment by wsjqkd** [comment]
您好，我也是中国一名研究生，请问该问题您解决了吗？对preprocessing文件下面各个库的版本里面没有提到，您是怎么确定的

**Comment by Jielin-Qiu** [comment]
Hi, thank you for your interest in our dataset. Could you send an email request with your affiliation email address? Thanks.

**Comment by wsjqkd** [comment]
My email address is ***@***.***



---Original---
From: ***@***.***&gt;
Date: Sat, Dec 7, 2024 06:57 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Jielin-Qiu/MMSum_model] Request for Assistance with MissingVideos in MMSum Dataset (Issue #8)




 
Hi, thank you for your interest in our dataset. Could you send an email request with your affiliation email address? Thanks.
